<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\fonts" />
    <None Remove="assets\namebending" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\namebending" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\MelonLoader\**\*.dll" Private="false" />
		<Reference Include="ModUI">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\Mods\UIFramework.dll</HintPath>
		</Reference>
		<Reference Include="RumbleModdingAPI">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\Mods\RumbleModdingAPI.dll</HintPath>
		</Reference>
	</ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;$(TargetPath)&quot; &quot;C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\Mods\$(TargetFileName)&quot;" />
  </Target>

</Project>
